on:
  workflow_run:
    workflows: ["Build"]
    branches: [de-husk/cargo-bump] # TODO: Switch to main once this is working
    types:
      - completed

name: Release

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: "github.event.workflow_run.conclusion == 'success' && !contains(github.event.pull_request.user.login, 'release-bot@dehusk.xyz')"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Install cargo cargo-edit
        run: cargo install cargo-edit

      - name: Bump cargo version
        run: cargo set-version --bump patch

      # TODO: Open a PR

  release:
    runs-on: ubuntu-latest
    # TODO: This check seems to be broken....
    if: "github.event.workflow_run.conclusion == 'success' && contains(github.event.pull_request.user.login, 'release-bot@dehusk.xyz')"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
